---
title: "Homework6"
author: "Kevin Gnaster, Zach Josten, Cade Balvanz"
date: "3/2/2022"
output: html_document
---

```{r}
data(happy, package="productplots")
HAPPY <- readRDS("HAPPY.rds")
```

# Part 1

### Question 1

Kevin Gnaster

```{r}
HAPPY = replace(HAPPY, HAPPY == "IAP", NA)
HAPPY = replace(HAPPY, HAPPY == "DK", NA)
HAPPY = replace(HAPPY, HAPPY == "NA", NA)
```

### Question 2

Kevin Gnaster

```{r}
library(dplyr)
HAPPY = HAPPY %>% mutate(
  age = replace(AGE, AGE == "89 AND OLDER", 89),
  age = as.numeric(age)) %>% select(-AGE)

HAPPY = HAPPY %>% mutate(HAPPY = factor(HAPPY), 
                         SEX = factor(SEX),
                         MARITAL = factor(MARITAL),
                         DEGREE = factor(DEGREE),
                         FINRELA = factor(FINRELA),
                         HEALTH = factor(HEALTH),
                         PARTYID = factor(PARTYID),
                         POLVIEWS = factor(POLVIEWS))
str(HAPPY)
```
### Question 3

```{r}
HAPPY$DEGREE <- factor(HAPPY$DEGREE, levels = c("lt high school", "high school", "junior college", "bachelor", "graduate school"))
```

